### ISSUE TITLE
Surprising redaction for RubyGem token

### ISSUE THREAD

**Issue by look** [github/redacting-logger#65]
The pattern for the RubyGem token is:

https://github.com/github/redacting-logger/blob/c078d9075b99cd8886e1632cf7cba21ce7bd7f6b/lib/patterns/default.rb#L50

However, the test is:

https://github.com/github/redacting-logger/blob/c078d9075b99cd8886e1632cf7cba21ce7bd7f6b/spec/lib/redacting_logger_spec.rb#L154-L158

This _should_ be `"using rubygems token: [REDACTED]"`, but it hits the GitHub token pattern instead:

https://github.com/github/redacting-logger/blob/c078d9075b99cd8886e1632cf7cba21ce7bd7f6b/lib/patterns/default.rb#L9

Possible fixes:

- Remove the RubyGem pattern because it's duplicative
- Change the GitHub token pattern to use `{40}` instead of `{40,}` so it doesn't match.

Aside: I think you could improve the performance of this library by combining all the regular expressions into a single regex to run once rather than looping over them until finding a match.

**Comment by GrantBirki** [comment]
@look I went ahead and just moved the `rubygems` pattern match in the array to fix the issue for now via https://github.com/github/redacting-logger/pull/66

I think what we will want to do long term is just have one jumbo regex that runs to help prevent this and also for performance gains so I will leave this issue open until that happens (one way or another).

**Comment by look** [comment]
> I think what we will want to do long term is just have one jumbo regex that runs to help prevent this and also for performance gains so I will leave this issue open until that happens (one way or another).

That is the approach I took in https://github.com/github/blackbird-mw/pull/2927.
